# Generated by Django 5.0.1 on 2024-02-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mob',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
